### PR TITLE
Fixed Some bugs and now Nether Wart can be cultivated

### PR DESCRIPTION
**Pull request by SkygridRex**

### CODE REVIEW

**Comment by DRedDogPE** [comment]
I was just about to do this too

**Comment by SkygridRex** [comment]
what thing

**Comment by DRedDogPE** [comment]
Also you need to add the item/FlowerPot.php back because at the moment it just keeps crashing

**Comment by SkygridRex** [comment]
i don't have time to check the code sorry

**Comment by DRedDogPE** [comment]
The travis checks it automatically you just have to open the details after you push a commit

**Comment by SkygridRex** [comment]
it's not needed add the item\flowerpot
php

**Comment by SkygridRex** [comment]
What happened with EliteCrafterz?

**Comment by DRedDogPE** [comment]
i am sorting out the hosting issues

**Pull request merged**
